services:
  frontend:
    image: smsc-management-fe-frontend:latest
    ports:
      - "80:80"
    environment:
      - BACKEND_IP=192.168.100.20:9087
      - NG_APP_FILTER_ONLY_SERVICE_PROVIDERS=false
