export const environment = {
  production: true,
  APIUrl: import.meta.env.NG_APP_API_URL,
  PatternIp: import.meta.env.NG_APP_PATTERN_IP,
  PatternSystemId: import.meta.env.NG_APP_PATTERN_SYSTEM_ID,
  PatternSystemLabel: import.meta.env.NG_APP_PATTERN_SYSTEM_LABEL,
  MaxLengthIp: import.meta.env.NG_APP_MAX_LENGTH_IP,
  PatternEmail: import.meta.env.NG_APP_PATTERN_EMAIL,
  timeOutWebsocket: import.meta.env.NG_APP_TIMEOUT_WEBSOCKET,
  filterOnlyServiceProviders: '___NG_APP_FILTER_ONLY_SERVICE_PROVIDERS___',
  filterOnlyGateways: '___NG_APP_FILTER_ONLY_GATEWAYS___',
  IpSmGwModule: import.meta.env.NG_APP_ENABLE_IP_SM_GW,
  ServiceProviderDefaults: {
    bind_type: import.meta.env.NG_APP_SP_BIND_TYPE,
    interface_version: import.meta.env.NG_APP_SP_INTERFACE_VERSION,
    sessions_number: import.meta.env.NG_APP_SP_SESSIONS_NUMBER,
    address_ton: import.meta.env.NG_APP_SP_ADDRESS_TON,
    address_npi: import.meta.env.NG_APP_SP_ADDRESS_NPI,
    address_range: import.meta.env.NG_APP_SP_ADDRESS_RANGE_REGEX,
    balance_type: import.meta.env.NG_APP_SP_BALANCE_TYPE,
    balance: import.meta.env.NG_APP_SP_BALANCE,
    tps: import.meta.env.NG_APP_SP_TPS,
    validity: import.meta.env.NG_APP_SP_VALIDITY,
    status: import.meta.env.NG_APP_SP_STATUS,
    enabled: import.meta.env.NG_APP_SP_ENABLED,
    enquire_link_period: import.meta.env.NG_APP_SP_ENQUIRE_LINK_PERIOD,
    pdu_timeout: import.meta.env.NG_APP_SP_PDU_TIMEOUT,
    request_dlr: import.meta.env.NG_APP_SP_REQUEST_DLR,
    contact_name: import.meta.env.NG_APP_SP_CONTACT_NAME,
    email: import.meta.env.NG_APP_SP_EMAIL,
    phone_number: import.meta.env.NG_APP_SP_PHONE_NUMBER,
    protocol: import.meta.env.NG_APP_SP_PROTOCOL,
    message_priority: import.meta.env.NG_APP_SP_PRIORITY
  },
  GatewaySmppDefaults: {
    bind_type: import.meta.env.NG_APP_GA_BIND_TYPE,
    interface_version: import.meta.env.NG_APP_GA_INTERFACE_VERSION,
    sessions_number: import.meta.env.NG_APP_GA_SESSIONS_NUMBER,
    address_ton: import.meta.env.NG_APP_GA_ADDRESS_TON,
    address_npi: import.meta.env.NG_APP_GA_ADDRESS_NPI,
    tps: import.meta.env.NG_APP_GA_TPS,
    status: import.meta.env.NG_APP_GA_STATUS,
    enabled: import.meta.env.NG_APP_GA_ENABLED,
    enquire_link_period: import.meta.env.NG_APP_GA_ENQUIRE_LINK_PERIOD,
    bind_timeout: import.meta.env.NG_APP_GA_BIND_TIMEOUT,
    bind_retry_period: import.meta.env.NG_APP_GA_BIND_RETRY_PERIOD,
    pdu_timeout: import.meta.env.NG_APP_GA_PDU_TIMEOUT,
    pdu_degree: import.meta.env.NG_APP_GA_PDU_DEGREE,
    thread_pool_size: import.meta.env.NG_APP_GA_THREAD_POOL_SIZE,
    request_dlr: import.meta.env.NG_APP_GA_REQUEST_DLR,
    protocol: import.meta.env.NG_APP_GA_PROTOCOL,
    encoding_iso88591: import.meta.env.NG_APP_GA_ENCODING_ISO8859,
    encoding_gsm7: import.meta.env.NG_APP_GA_ENCODING_GSM7,
    encoding_ucs2: import.meta.env.NG_APP_GA_ENCODING_UCS2,
    split_message: import.meta.env.NG_APP_GA_SPLIT_MESSAGE,
    split_smpp_type: import.meta.env.NG_APP_GA_SPLIT_SMPP_TYPE
  },
  GatewaySs7Defaults: {
    status: import.meta.env.NG_APP_GA_SS7_STATUS,
    enabled: import.meta.env.NG_APP_GA_SS7_ENABLED,
    global_title: import.meta.env.NG_APP_GA_SS7_GLOBAL_TITLE,
    global_title_indicator: import.meta.env.NG_APP_GA_SS7_GLOBAL_TITLE_INDICATOR,
    translation_type: import.meta.env.NG_APP_GA_SS7_TRANSLATION_TYPE,
    smsc_ssn: import.meta.env.NG_APP_GA_SS7_SMSC_SSN,
    hlr_ssn: import.meta.env.NG_APP_GA_SS7_HLR_SSN,
    msc_ssn: import.meta.env.NG_APP_GA_SS7_MSC_SSN,
    map_version: import.meta.env.NG_APP_GA_SS7_MAP_VERSION,
    split_message: import.meta.env.NG_APP_GA_SS7_SPLIT_MESSAGE,
    home_routing: import.meta.env.NG_APP_GA_SS7_HOME_ROUTING,
    hss_update_enabled: import.meta.env.NG_APP_GA_SS7_HSS_UPDATE_ENABLED,
    allowed_traffic: import.meta.env.NG_APP_GA_SS7_ALLOWED_TRAFFIC,
    allowed_ussi: import.meta.env.NG_APP_GA_SS7_ALLOWED_USSI,
    tcap: {
      ssn_list: import.meta.env.NG_APP_GA_SS7_TCAP_SSN_LIST,
      preview_mode: import.meta.env.NG_APP_GA_SS7_TCAP_PREVIEW_MODE,
      invoke_timeout: import.meta.env.NG_APP_GA_SS7_TCAP_INVOKE_TIMEOUT,
      dialog_timeout: import.meta.env.NG_APP_GA_SS7_TCAP_DIALOG_TIMEOUT,
      dialog_range_start: import.meta.env.NG_APP_GA_SS7_TCAP_DIALOG_RANGE_START,
      dialog_range_end: import.meta.env.NG_APP_GA_SS7_TCAP_DIALOG_RANGE_END,
      max_dialogs: import.meta.env.NG_APP_GA_SS7_TCAP_MAX_DIALOGS,
      do_not_send: import.meta.env.NG_APP_GA_SS7_TCAP_DO_NOT_SEND,
      swap_tcap: import.meta.env.NG_APP_GA_SS7_TCAP_SWAP_TCAP,
      sls_range: import.meta.env.NG_APP_GA_SS7_TCAP_SLS_RANGE,
      exr_delay_thr_1: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_DELAY_THR1,
      exr_delay_thr_2: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_DELAY_THR2,
      exr_delay_thr_3: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_DELAY_THR3,
      exr_normal_delay_thr_1: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_NORMAL_DELAY_THR1,
      exr_normal_delay_thr_2: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_NORMAL_DELAY_THR2,
      exr_normal_delay_thr_3: import.meta.env.NG_APP_GA_SS7_TCAP_EXR_NORMAL_DELAY_THR3,
      memory_monitor_thr_1: import.meta.env.NG_APP_GA_SS7_TCAP_MEMORY_MONITOR_THR1,
      memory_monitor_thr_2: import.meta.env.NG_APP_GA_SS7_TCAP_MEMORY_MONITOR_THR2,
      memory_monitor_thr_3: import.meta.env.NG_APP_GA_SS7_TCAP_MEMORY_MONITOR_THR3,
      mem_normal_delay_thr_1: import.meta.env.NG_APP_GA_SS7_TCAP_MEM_NORMAL_DELAY_THR1,
      mem_normal_delay_thr_2: import.meta.env.NG_APP_GA_SS7_TCAP_MEM_NORMAL_DELAY_THR2,
      mem_normal_delay_thr_3: import.meta.env.NG_APP_GA_SS7_TCAP_MEM_NORMAL_DELAY_THR3,
      blocking_tcap: import.meta.env.NG_APP_GA_SS7_TCAP_BLOCKING_TCAP
    },
    map: {
      sri_service_op_code: import.meta.env.NG_APP_GA_SS7_MAP_SRI_SERVICE_OP_CODE,
      forward_sm_service_op_code: import.meta.env.NG_APP_GA_SS7_MAP_FORWARD_SM_SERVICE
    },
    m3ua: {
      CONNECT_DELAY: import.meta.env.NG_APP_GA_SS7_M3UA_CONNECT_DELAY,
      DELIVER_MESSAGE_THREAD_COUNT: import.meta.env.NG_APP_GA_SS7_M3UA_DELIVER_MESSAGE_THREAD_COUNT,
      HEARTBEAT_TIME: import.meta.env.NG_APP_GA_SS7_M3UA_HEARTBEAT_TIME,
      ROUTING_KEY_MANAGEMENT_ENABLED: import.meta.env.NG_APP_GA_SS7_M3UA_ROUTING_KEY_MANAGEMENT_ENABLED,
      USE_LOWEST_BIT_FOR_LINK: import.meta.env.NG_APP_GA_SS7_M3UA_USE_LOWEST_BIT_FOR_LINK,
      CC_DELAY_THRESHOLD_1: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_THRESHOLD_1,
      CC_DELAY_THRESHOLD_2: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_THRESHOLD_2,
      CC_DELAY_THRESHOLD_3: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_THRESHOLD_3,
      CC_DELAY_BACK_TO_NORMAL_THRESHOLD_1: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_BACK_TO_NORMAL_THRESHOLD_1,
      CC_DELAY_BACK_TO_NORMAL_THRESHOLD_2: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_BACK_TO_NORMAL_THRESHOLD_2,
      CC_DELAY_BACK_TO_NORMAL_THRESHOLD_3: import.meta.env.NG_APP_GA_SS7_M3UA_CC_DELAY_BACK_TO_NORMAL_THRESHOLD_3,
      sockets: {
        socket_type: import.meta.env.NG_APP_GA_SS7_M3UA_SOCKET_TYPE,
      }
    },
    sccp: {
      zmarin: import.meta.env.NG_APP_GA_SS7_SCCP_ZMARGIN,
      remove_spc: import.meta.env.NG_APP_GA_SS7_SCCP_REMOVE_SPC,
      sst_timer_min: import.meta.env.NG_APP_GA_SS7_SCCP_SST_TIMER_MIN,
      sst_timer_max: import.meta.env.NG_APP_GA_SS7_SCCP_SST_TIMER_MAX,
      sst_timer_increase_factor: import.meta.env.NG_APP_GA_SS7_SCCP_SST_TIMER_INCREASE_FACTOR,
      max_data_message: import.meta.env.NG_APP_GA_SS7_SCCP_MAX_DATA_MESSAGE,
      period_of_logging: import.meta.env.NG_APP_GA_SS7_SCCP_PERIOD_OF_LOGGING,
      reassembly_timer: import.meta.env.NG_APP_GA_SS7_SCCP_REASSEMBLY_TIMER,
      preview_mode: import.meta.env.NG_APP_GA_SS7_SCCP_PREVIEW_MODE,
      sccp_protocol_version: import.meta.env.NG_APP_GA_SS7_SCCP_SCCP_PROTOCOL_VERSION,
      congestion_control_timer_a: import.meta.env.NG_APP_GA_SS7_SCCP_CONGESTION_CONTROL_TIMER_A,
      congestion_control_timer_d: import.meta.env.NG_APP_GA_SS7_SCCP_CONGESTION_CONTROL_TIMER_D,
      congestion_control_algorithm: import.meta.env.NG_APP_GA_SS7_SCCP_CONGESTION_CONTROL_ALGORITHM,
      congestion_control_outgoing: import.meta.env.NG_APP_GA_SS7_SCCP_CONGESTION_CONTROL_OUTGOING
    },
  },
  RulesServiceProviderDefaults: {
    source_addr_ton: import.meta.env.NG_APP_SOURCE_ADDR_TON,
    source_addr_npi: import.meta.env.NG_APP_SOURCE_ADDR_NPI,
    dest_addr_ton: import.meta.env.NG_APP_DEST_ADDR_TON,
    dest_addr_npi: import.meta.env.NG_APP_DEST_ADDR_NPI
  },
  generalSettings: {
    general: {
      encoding_iso88591: import.meta.env.NG_APP_G_SETTINGS_ENCODING_ISO8859,
      encoding_gsm7: import.meta.env.NG_APP_G_SETTINGS_ENCODING_GSM7,
      encoding_ucs2: import.meta.env.NG_APP_G_SETTINGS_ENCODING_UCS2,
      max_password_length: import.meta.env.NG_APP_G_SETTINGS_MAX_PASSWORD_LENGTH,
      max_system_id_length: import.meta.env.NG_APP_G_SETTINGS_MAX_SYSTEM_ID_LENGTH
    },
    retries: {
      firstRetryDelay: import.meta.env.NG_APP_RETRY_FIRST_DELAY,
      maxDueDelay: import.meta.env.NG_APP_RETRY_MAX,
      retryDelayMultiplier: import.meta.env.NG_APP_RETRY_DELAY,
    }
  },
  dtOptions: {
    pagingType: "simple_numbers",
    pageLength: import.meta.env.NG_APP_DT_PAGE_LENGTH,
    lengthMenu: import.meta.env.NG_APP_DT_LENGTH_MENU.split(','),
    scrollX: false,
    autoWidth: true,
    destroy: true,
    responsive: true,
    searching: true,
    info: true,
    order: [[0, import.meta.env.NG_APP_DT_ORDER]],
    columnDefs: [
      { targets: '_all', className: 'dt-nowrap' }
    ],
  },
  smppServerListenerConfig: {
    status: import.meta.env.NG_APP_SMPP_SERVER_STATUS,
    enabled: import.meta.env.NG_APP_SMPP_SERVER_ENABLED,
  },
  broadcastAllowedExtensions: import.meta.env.NG_APP_BROADCAST_ALLOWED_EXTENSIONS,
};