export interface GatewayHttp {
  network_id: number;
  name: string;
  system_id: string;
  password: string;
  ip: string;
  port: number;
  bind_type: string;
  system_type: string;
  interface_version: string;
  sessions_number: number;
  address_ton: number;
  address_npi: number;
  address_range: string;
  messages_per_second_high: number;
  messages_per_second_medium: number;
  messages_per_second_low: number;
  messages_per_second: number;
  enabled: number;
  enquire_link_period: number;
  request_dlr: boolean;
  auto_retry_error_code: string;
  no_retry_error_code: string;
  retry_alternate_destination_error_code: string;
  bind_timeout: number;
  bind_retry_period: number;
  pdu_timeout: number;
  pdu_degree: number;
  thread_pool_size: number;
  mno_id: number;
  status: string;
  active_sessions_numbers: number;
  protocol: string;
  encoding_iso88591: string;
  encoding_gsm7: string,
  encoding_ucs2: string,
  split_message: boolean,
  split_smpp_type: string
}
